server.port=8080
spring.jackson.date-format=com.jio.productorder.RFC3339DateFormat
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

# MariaDB DataSource
spring.datasource.url=jdbc:mariadb://localhost:3306/jio_product_order
spring.datasource.username=root
spring.datasource.password=Saanvi@999
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Downstream service URLs
services.tmf629.url=http://localhost:8083
services.tmf620.url=http://localhost:8081
services.tmf637.url=http://localhost:8084
