-- Payment module schema. Flyway is the single source of truth; Hibernate runs in validate mode.

-- ---------------------------------------------------------------------------
-- Core TMF676 / TMF670 resources
-- ---------------------------------------------------------------------------

CREATE TABLE payment (
    id                     VARCHAR(64)   PRIMARY KEY,
    correlator_id          VARCHAR(255),
    status                 VARCHAR(40)   NOT NULL,
    amount_value           NUMERIC(19, 4),
    amount_currency        VARCHAR(3),
    total_amount_value     NUMERIC(19, 4),
    total_amount_currency  VARCHAR(3),
    tax_amount_value       NUMERIC(19, 4),
    tax_amount_currency    VARCHAR(3),
    captured_amount        NUMERIC(19, 4) NOT NULL DEFAULT 0,
    refunded_amount        NUMERIC(19, 4) NOT NULL DEFAULT 0,
    authorization_code     VARCHAR(255),
    description            VARCHAR(1024),
    name                   VARCHAR(255),
    account_id             VARCHAR(64),
    payment_method_id      VARCHAR(64),
    psp_reference          VARCHAR(255),
    payment_date           TIMESTAMPTZ,
    status_date            TIMESTAMPTZ,
    dto_json               JSONB,
    created_at             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version                BIGINT        NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX ux_payment_correlator ON payment (correlator_id) WHERE correlator_id IS NOT NULL;
CREATE INDEX ix_payment_status ON payment (status);

CREATE TABLE payment_method (
    id                  VARCHAR(64)  PRIMARY KEY,
    type                VARCHAR(40)  NOT NULL,
    name                VARCHAR(255) NOT NULL,
    description         VARCHAR(1024),
    is_preferred        BOOLEAN,
    authorization_code  VARCHAR(255),
    status              VARCHAR(40),
    status_reason       VARCHAR(255),
    status_date         TIMESTAMPTZ,
    account_id          VARCHAR(64),
    token_ref           VARCHAR(255),
    valid_for_start     TIMESTAMPTZ,
    valid_for_end       TIMESTAMPTZ,
    dto_json            JSONB,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version             BIGINT       NOT NULL DEFAULT 0
);

CREATE TABLE refund (
    id                     VARCHAR(64)   PRIMARY KEY,
    correlator_id          VARCHAR(255),
    payment_id             VARCHAR(64)   NOT NULL REFERENCES payment (id),
    status                 VARCHAR(40)   NOT NULL,
    amount_value           NUMERIC(19, 4),
    amount_currency        VARCHAR(3),
    total_amount_value     NUMERIC(19, 4),
    total_amount_currency  VARCHAR(3),
    tax_amount_value       NUMERIC(19, 4),
    tax_amount_currency    VARCHAR(3),
    authorization_code     VARCHAR(255),
    description            VARCHAR(1024),
    name                   VARCHAR(255),
    account_id             VARCHAR(64),
    payment_method_id      VARCHAR(64),
    psp_reference          VARCHAR(255),
    refund_kind            VARCHAR(20),
    refund_date            TIMESTAMPTZ,
    status_date            TIMESTAMPTZ,
    dto_json               JSONB,
    created_at             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version                BIGINT        NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX ux_refund_correlator ON refund (correlator_id) WHERE correlator_id IS NOT NULL;
CREATE INDEX ix_refund_payment ON refund (payment_id);

-- ---------------------------------------------------------------------------
-- Append-only audit trail
-- ---------------------------------------------------------------------------

CREATE TABLE payment_state_transition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id      VARCHAR(64)  NOT NULL,
    from_state      VARCHAR(40),
    to_state        VARCHAR(40)  NOT NULL,
    reason          VARCHAR(255),
    correlation_id  VARCHAR(255),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_transition_payment ON payment_state_transition (payment_id);

CREATE TABLE payment_audit (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type     VARCHAR(40)  NOT NULL,
    entity_id       VARCHAR(64)  NOT NULL,
    action          VARCHAR(64)  NOT NULL,
    detail          JSONB,
    correlation_id  VARCHAR(255),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_audit_entity ON payment_audit (entity_type, entity_id);

-- Enforce append-only at the database level.
CREATE OR REPLACE FUNCTION payments_forbid_mutation() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'Table % is append-only (% not allowed)', TG_TABLE_NAME, TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_transition_append_only
    BEFORE UPDATE OR DELETE ON payment_state_transition
    FOR EACH ROW EXECUTE FUNCTION payments_forbid_mutation();

CREATE TRIGGER trg_audit_append_only
    BEFORE UPDATE OR DELETE ON payment_audit
    FOR EACH ROW EXECUTE FUNCTION payments_forbid_mutation();

-- ---------------------------------------------------------------------------
-- Idempotency + webhook de-duplication
-- ---------------------------------------------------------------------------

CREATE TABLE idempotency_record (
    idem_key              VARCHAR(255) PRIMARY KEY,
    operation             VARCHAR(64)  NOT NULL,
    request_hash          VARCHAR(128),
    status                VARCHAR(20)  NOT NULL,
    response_entity_id    VARCHAR(64),
    response_status_code  INTEGER,
    response_body         JSONB,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at            TIMESTAMPTZ
);

CREATE TABLE processed_webhook (
    event_id     VARCHAR(255) PRIMARY KEY,
    provider     VARCHAR(64)  NOT NULL,
    payment_id   VARCHAR(64),
    received_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Transactional outbox (events)
-- ---------------------------------------------------------------------------

CREATE TABLE outbox_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type  VARCHAR(64)  NOT NULL,
    aggregate_id    VARCHAR(64)  NOT NULL,
    event_type      VARCHAR(128) NOT NULL,
    topic           VARCHAR(128) NOT NULL,
    payload         JSONB        NOT NULL,
    published       BOOLEAN      NOT NULL DEFAULT FALSE,
    attempts        INTEGER      NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    published_at    TIMESTAMPTZ
);
CREATE INDEX ix_outbox_unpublished ON outbox_event (published, created_at) WHERE published = FALSE;

-- ---------------------------------------------------------------------------
-- Dunning
-- ---------------------------------------------------------------------------

CREATE TABLE dunning_attempt (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id       VARCHAR(64)  NOT NULL,
    attempt_number   INTEGER      NOT NULL,
    status           VARCHAR(20)  NOT NULL,
    next_attempt_at  TIMESTAMPTZ,
    last_error       VARCHAR(1024),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_dunning_due ON dunning_attempt (status, next_attempt_at);

-- ---------------------------------------------------------------------------
-- Reconciliation
-- ---------------------------------------------------------------------------

CREATE TABLE reconciliation_exception (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_ref   VARCHAR(255),
    payment_id       VARCHAR(64),
    file_name        VARCHAR(255),
    reason           VARCHAR(64)   NOT NULL,
    expected_amount  NUMERIC(19, 4),
    actual_amount    NUMERIC(19, 4),
    detail           JSONB,
    resolved         BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- ShedLock (once-only scheduled execution across instances)
-- ---------------------------------------------------------------------------

CREATE TABLE shedlock (
    name        VARCHAR(64)  PRIMARY KEY,
    lock_until  TIMESTAMPTZ  NOT NULL,
    locked_at   TIMESTAMPTZ  NOT NULL,
    locked_by   VARCHAR(255) NOT NULL
);
